import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css"; 
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import LinedBackground from "@/components/ui/LinedBackground";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";

const ObjectSans = localFont({
  src: [
    {
      path: './fonts/ObjectSans.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ObjectSans-Heavy.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-objectSans',
});

const PlaypenSansArabic = localFont({
  src: [
    {
      path: './fonts/playpen-sans-arabic-400.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/playpen-sans-arabic-600.woff2',
      weight: '600',
      style: 'normal',
    },
  ],

  display: 'swap',
  variable: '--font-playpenSansArabic',
});

export const metadata: Metadata = {
  title: "Bishoy Morgan | Freelance Web Developer",
  description: "Generated by Morgan",
};

const locales = ['en', 'es', 'ar'];

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <head>
        {process.env.NEXT_PUBLIC_GA_ID && (
          <>
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
              strategy="afterInteractive"
            />
            <Script id="ga-init" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
              `}
            </Script>
          </>
        )}
      </head>
      <body 
        dir={locale === "ar" ? "rtl" : "ltr"}
        className={
          locale === "ar"
            ? `${PlaypenSansArabic.className} antialiased`
            : `${ObjectSans.className} antialiased`
        }
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LinedBackground />
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}